version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - redis-data:/data

  multiplayerlobbygame-api:
    image: multiplayerlobbygame-api
    expose:
      - "5001"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RedisConnection=redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    scale: 3 # Run 3 instances of the app
    restart: unless-stopped
    volumes:
      - redis-data:/app

volumes:
    redis-data:

networks:
  app-network:
    driver: bridge