version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  multiplayerlobbygame-api:
    image: multiplayerlobbygame-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RedisConnection=redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    scale: 3 # Run 3 instances of the app

networks:
  app-network:
    driver: bridge