version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - redis-data:/data

  multiplayerlobbygame-api:
    image: multiplayerlobbygame-api
    ports:
      - "5000-5050:5000"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://127.0.0.1:5000
      - ASPNETCORE_ENVIRONMENT=Production
      - RedisConnection=redis:6379
    depends_on:
      - redis
    networks:
      - app-network

volumes:
    redis-data:

networks:
  app-network:
    driver: bridge